ABORTED                  = -1
FAILURE                  =  0
SUCCESS                  =  1

INITIALIZE               =  2
SET                      =  3
GET                      =  4
START                    =  5
STOP                     =  6
RELEASE                  =  7

IMAGE_SHAPE_DEFAULT      =  (1080,1440)

FRAMERATE_PROPERTY_ID    =  8
FRAMERATE_PROPERTY_NAME  =  'framerate'
FRAMERATE_PROPERTY_UNITS =  'fps'
FRAMERATE_PROPERTY_TYPE  =  int
FRAMERATE_MINIMUM_VALUE  =  1
FRAMERATE_MAXIMUM_VALUE  =  120
FRAMERATE_INVALID_VALUE  =  None
FRAMERATE_DEFAULT_VALUE  =  30

EXPOSURE_PROPERTY_ID     =  9
EXPOSURE_PROPERTY_NAME   =  'exposure'
EXPOSURE_PROPERTY_UNITS  =  'us'
EXPOSURE_PROPERTY_TYPE   =  int
EXPOSURE_MINIMUM_VALUE   =  100
EXPOSURE_MAXIMUM_VALUE   =  100000
EXPOSURE_INVALID_VALUE   =  None
EXPOSURE_DEFAULT_VALUE   =  1500

BINSIZE_PROPERTY_ID      =  10
BINSIZE_PROPERTY_NAME    =  'binsize'
BINSIZE_PROPERTY_UNITS   =  'pixels'
BINSIZE_PROPERTY_TYPE    =  int
BINSIZE_MINIMUM_VALUE    =  1
BINSIZE_MAXIMUM_VALUE    =  4
BINSIZE_INVALID_VALUE    =  3
BINSIZE_DEFAULT_VALUE    =  1
